schema = 3

[mod]
  [mod."buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go"]
    version = "v1.32.0-20231115204500-e097f827e652.1"
    hash = "sha256-z+s4I7K/QKi/I2gUxc0u0Y/DQG6GZC4Yg/snFw3Ahyk="
  [mod."dario.cat/mergo"]
    version = "v1.0.0"
    hash = "sha256-jlpc8dDj+DmiOU4gEawBu8poJJj9My0s9Mvuk9oS8ww="
  [mod."github.com/BurntSushi/toml"]
    version = "v0.3.1"
    hash = "sha256-Rqak1dE/Aj/+Kx1/pl3Hifgt+Q3OzuZ5fJR+/x3nTbo="
  [mod."github.com/CycloneDX/cyclonedx-go"]
    version = "v0.8.0"
    hash = "sha256-+0asm6u04aZvkf+6OtQIQa8stksKohVnZS3w/PYeKho="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.1"
    hash = "sha256-BL0BVaHtmPKQts/711W59AbHXjGKqFS4ZTal0RYnR9I="
  [mod."github.com/OneOfOne/xxhash"]
    version = "v1.2.8"
    hash = "sha256-28mtDA8BHI8jHaD991ZEd0Ml3I1QT+SkvzD9I4DCcAM="
  [mod."github.com/ProtonMail/go-crypto"]
    version = "v0.0.0-20230828082145-3c4c8a2d2371"
    hash = "sha256-YxAaQgQoTOhD8hE+aT+T8ytKKxcQW6tgoL2MAU7nTvo="
  [mod."github.com/agext/levenshtein"]
    version = "v1.2.3"
    hash = "sha256-d1lUB0kToOsPYfRmEh9SO+iVipgmsRs4xQkj1xlY9og="
  [mod."github.com/anchore/go-struct-converter"]
    version = "v0.0.0-20230627203149-c72ef8859ca9"
    hash = "sha256-oogLVAW9maN2kRED2JXvXBQlgSkJTY66Dai4PRJ1WRo="
  [mod."github.com/apparentlymart/go-textseg/v13"]
    version = "v13.0.0"
    hash = "sha256-Hn+zO0J/vnG5U6JvZfRyWm8vsqYdjh4RAreWnZLCQKQ="
  [mod."github.com/apparentlymart/go-textseg/v15"]
    version = "v15.0.0"
    hash = "sha256-960kVVQSGhx1Gww5cfoNeM3yXaA4dwlv+AFhKh6EGlA="
  [mod."github.com/atotto/clipboard"]
    version = "v0.1.4"
    hash = "sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk="
  [mod."github.com/awalterschulze/gographviz"]
    version = "v2.0.3+incompatible"
    hash = "sha256-NLQtom5/csYWGUq3IMds0OI69S+/VDalAYccExFJ7Qc="
  [mod."github.com/aymanbagabas/go-osc52/v2"]
    version = "v2.0.1"
    hash = "sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg="
  [mod."github.com/bom-squad/protobom"]
    version = "v0.3.0"
    hash = "sha256-KKF8GwpCYDX1L2s7bmlY+hMoLmnb5ZnD64linuDNEhU="
  [mod."github.com/buildsafedev/bsf-apis"]
    version = "v0.0.0-20240301225559-0cabfd4c881d"
    hash = "sha256-n96xOkL2y6h1OlY513vW0tlUrOc6ICVYMTW9sh0I5sE="
  [mod."github.com/cespare/xxhash"]
    version = "v1.1.0"
    hash = "sha256-nVDTtXH9PC3yJ0THaQZEN243UP9xgLi/clt5xRqj3+M="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/charmbracelet/bubbles"]
    version = "v0.16.1"
    hash = "sha256-Z/H2bliHQttBM1mJmY3umFGl+RAcN5MgXpDcr1e/1O4="
  [mod."github.com/charmbracelet/bubbletea"]
    version = "v0.24.2"
    hash = "sha256-UszAKKLThTPegAJxdLJQmt5veVLroC5ww42atVk+SjM="
  [mod."github.com/charmbracelet/lipgloss"]
    version = "v0.7.1"
    hash = "sha256-GdPbyi762tGmU0ASLv76/DDjOubYp6K1kNio/IUVUiQ="
  [mod."github.com/cloudflare/circl"]
    version = "v1.3.7"
    hash = "sha256-AkOpcZ+evLxLJStvvr01+TLeWDqcLxY3e/AhGggzh40="
  [mod."github.com/common-nighthawk/go-figure"]
    version = "v0.0.0-20210622060536-734e95fb86be"
    hash = "sha256-vI9YAz3OE+7uUkhKhqTyrMvmdM82wKpBURq9uTLFwX4="
  [mod."github.com/containerd/console"]
    version = "v1.0.4-0.20230313162750-1ae8d489ac81"
    hash = "sha256-Qus81DgpWHJ6RRqeKOKcUFvzCxvPzygJqBabvBsBuHU="
  [mod."github.com/cyphar/filepath-securejoin"]
    version = "v0.2.4"
    hash = "sha256-heCD0xMxlwnHCHcRBgTjVexHOLyWI2zRW3E8NFKoLzk="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/dgraph-io/badger/v3"]
    version = "v3.2103.2"
    hash = "sha256-F6pvsaSKwXOl9RfnUQFqAl6xpCVu9+rthQgOxhKVk1g="
  [mod."github.com/dgraph-io/ristretto"]
    version = "v0.1.0"
    hash = "sha256-01jneg1+1x8tTfUTBZ+6mHkQaqXVnPYxLJyJhJQcvt4="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/elewis787/boa"]
    version = "v0.1.2"
    hash = "sha256-W78mgqVJLXsy37KBBCAx6dIJzrJtPhbMmdGNWIQtzho="
  [mod."github.com/emirpasic/gods"]
    version = "v1.18.1"
    hash = "sha256-hGDKddjLj+5dn2woHtXKUdd49/3xdsqnhx7VEdCu1m4="
  [mod."github.com/go-git/gcfg"]
    version = "v1.5.1-0.20230307220236-3a3c6141e376"
    hash = "sha256-f4k0gSYuo0/q3WOoTxl2eFaj7WZpdz29ih6CKc8Ude8="
  [mod."github.com/go-git/go-billy/v5"]
    version = "v5.5.0"
    hash = "sha256-4XUoD2bOCMCdu83egb/y8kY/Fm0s1rWgPMtiahh38OQ="
  [mod."github.com/go-git/go-git/v5"]
    version = "v5.11.0"
    hash = "sha256-2yUM/FlV+nYxacVynJCnDZeMub4Iu8JL2WBHmlnwOkE="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/glog"]
    version = "v1.2.0"
    hash = "sha256-eCWkUlsWbHSjsuTw8HcNpj3KxT+QPvW5SSIv88hAsxA="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.4"
    hash = "sha256-N3+Lv9lEZjrdOWdQhFj6Y3Iap4rVLEQeI8/eFFyAMZ0="
  [mod."github.com/golang/snappy"]
    version = "v0.0.3"
    hash = "sha256-77y8JFRE3FcYd8CTypXnJlTJuog1pJg5WjhboFjTiLU="
  [mod."github.com/google/flatbuffers"]
    version = "v1.12.1"
    hash = "sha256-v9/ewAmNdQ4SNBlBwgHkxn3IVJAf31D7zVlxwEK/LRs="
  [mod."github.com/google/go-cmp"]
    version = "v0.6.0"
    hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg="
  [mod."github.com/google/go-github/v62"]
    version = "v62.0.0"
    hash = "sha256-vQsgaNI69lUSAPmjHo8gytnpYMtAdEKKNljF9t5NzsY="
  [mod."github.com/google/go-querystring"]
    version = "v1.1.0"
    hash = "sha256-itsKgKghuX26czU79cK6C2n+lc27jm5Dw1XbIRgwZJY="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.19.1"
    hash = "sha256-rCFj39yIjx/xX99OSAncloxaJP1IJG59fK2CwU5M2WY="
  [mod."github.com/hashicorp/hcl/v2"]
    version = "v2.19.1"
    hash = "sha256-K1bdbe8HBT5440qjU2kw5aUXfA1kkJaHdd/2DmY6CBs="
  [mod."github.com/in-toto/in-toto-golang"]
    version = "v0.9.0"
    hash = "sha256-7PMF1ENUvwYER2vlUMuMYIkiG1GzvCq++jYpN3ICFe8="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jbenet/go-context"]
    version = "v0.0.0-20150711004518-d14ea06fba99"
    hash = "sha256-VANNCWNNpARH/ILQV9sCQsBWgyL2iFT+4AHZREpxIWE="
  [mod."github.com/jedib0t/go-pretty/v6"]
    version = "v6.5.9"
    hash = "sha256-gyBH+7amL9orNtnc9sek2dxAEG92mSpNuMRkaM9BT1A="
  [mod."github.com/kevinburke/ssh_config"]
    version = "v1.2.0"
    hash = "sha256-Ta7ZOmyX8gG5tzWbY2oES70EJPfI90U7CIJS9EAce0s="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.2"
    hash = "sha256-LlMbNhqmgQwUe4KKFK03R17S+gUo0/wPqmIFiwUb6Tg="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.0.9"
    hash = "sha256-0rHlHzEVaDdkVbRJDhnAJjfJUmAHOYjXN5u7VoCi5uk="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.2.0"
    hash = "sha256-Gg9dDJFCTaHrKHRR1SrJgZ8fWieJkybljybkI9x0gyE="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.19"
    hash = "sha256-wYQqGxeqV3Elkmn26Md8mKZ/viw598R4Ych3vtt72YE="
  [mod."github.com/mattn/go-localereader"]
    version = "v0.0.1"
    hash = "sha256-JlWckeGaWG+bXK8l8WEdZqmSiTwCA8b1qbmBKa/Fj3E="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.15"
    hash = "sha256-WP39EU2UrQbByYfnwrkBDoKN7xzXsBssDq3pNryBGm0="
  [mod."github.com/minio/sha256-simd"]
    version = "v1.0.0"
    hash = "sha256-oEo/BoMqSLdwSjrhHTiFjl5Om4MVLNQXDJINk6Z110Y="
  [mod."github.com/mitchellh/go-wordwrap"]
    version = "v0.0.0-20150314170334-ad45545899c7"
    hash = "sha256-aR+xW4TnVo96Cbw168fhdIBEh7O43mOlHdLx/WxrwVs="
  [mod."github.com/mr-tron/base58"]
    version = "v1.2.0"
    hash = "sha256-8FzMu3kHUbBX10pUdtGf59Ag7BNupx8ZHeUaodR1/Vk="
  [mod."github.com/muesli/ansi"]
    version = "v0.0.0-20230316100256-276c6243b2f6"
    hash = "sha256-qRKn0Bh2yvP0QxeEMeZe11Vz0BPFIkVcleKsPeybKMs="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/muesli/reflow"]
    version = "v0.3.0"
    hash = "sha256-Pou2ybE9SFSZG6YfZLVV1Eyfm+X4FuVpDPLxhpn47Cc="
  [mod."github.com/muesli/termenv"]
    version = "v0.15.2"
    hash = "sha256-Eum/SpyytcNIchANPkG4bYGBgcezLgej7j/+6IhqoMU="
  [mod."github.com/multiformats/go-multihash"]
    version = "v0.2.1"
    hash = "sha256-RWyw05s4Wnz44J2YzPkJAK/A4l5V4ZGk/c2I4lW18wc="
  [mod."github.com/multiformats/go-varint"]
    version = "v0.0.6"
    hash = "sha256-QlY6AzrSB/8IrlINPi8J8uw1J0SOa2UMTtlo79fg9gM="
  [mod."github.com/nix-community/go-nix"]
    version = "v0.0.0-20231219074122-93cb24a86856"
    hash = "sha256-gCRU9d4tuGP70i2IA2pl+ZcowHrWfN4mdOnQQR7AnH4="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/opencontainers/image-spec"]
    version = "v1.1.0"
    hash = "sha256-5OxW1ShHypLpzVu+BJivNlFX2JFPh9WKfJcMIgPZf4U="
  [mod."github.com/pjbgf/sha1cd"]
    version = "v0.3.0"
    hash = "sha256-kX9BdLh2dxtGNaDvc24NORO+C0AZ7JzbrXrtecCdB7w="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.4"
    hash = "sha256-B8tbL9K6ICLdm0lEhs9+h4cpjAfvFtNiFMGvQZmw0bM="
  [mod."github.com/sahilm/fuzzy"]
    version = "v0.1.0"
    hash = "sha256-69GT+9rw7Wzdn1QDUoC5oFsEjf378N14yHDKhxfN3PQ="
  [mod."github.com/secure-systems-lab/go-securesystemslib"]
    version = "v0.7.0"
    hash = "sha256-HyfI6b26Ja2xdMKSIF5FcXU0CeE0TaQptscs+7/vfPM="
  [mod."github.com/sergi/go-diff"]
    version = "v1.1.0"
    hash = "sha256-8NJMabldpf40uwQN20T6QXx5KORDibCBJL02KD661xY="
  [mod."github.com/shibumi/go-pathspec"]
    version = "v1.3.0"
    hash = "sha256-ZHLft/o+xyJrUlaCwnCDqbjkPj6iIxlOuA0fFBuwVvM="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.3"
    hash = "sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms="
  [mod."github.com/skeema/knownhosts"]
    version = "v1.2.1"
    hash = "sha256-u0jB6ahTdGa+SvcIvPNRLnbSHvgmW9X/ThRq0nWQrJs="
  [mod."github.com/spaolacci/murmur3"]
    version = "v1.1.0"
    hash = "sha256-RWD4PPrlAsZZ8Xy356MBxpj+/NZI7w2XOU14Ob7/Y9M="
  [mod."github.com/spdx/tools-golang"]
    version = "v0.5.3"
    hash = "sha256-2UcA7M19dPmcASm9pP1z2XEOm7z8bSmQS8+WeahFI0o="
  [mod."github.com/spf13/cobra"]
    version = "v1.8.0"
    hash = "sha256-oAE+fEaRfZPE541IPWE0GMeBBYgH2DMhtZNxzp7DFlY="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stretchr/testify"]
    version = "v1.8.4"
    hash = "sha256-MoOmRzbz9QgiJ+OOBo5h5/LbilhJfRUryvzHJmXAWjo="
  [mod."github.com/tidwall/gjson"]
    version = "v1.17.1"
    hash = "sha256-5R38cFZFaVbdem2B+9rsbr+0hRxbtDQ0i5PYWPT6kj0="
  [mod."github.com/tidwall/match"]
    version = "v1.1.1"
    hash = "sha256-M2klhPId3Q3T3VGkSbOkYl/2nLHnsG+yMbXkPkyrRdg="
  [mod."github.com/tidwall/pretty"]
    version = "v1.2.0"
    hash = "sha256-esRQGsn2Ee/CiySlwyuOICSLdqUkH4P7u8qXszos8Yc="
  [mod."github.com/xanzy/ssh-agent"]
    version = "v0.3.3"
    hash = "sha256-l3pGB6IdzcPA/HLk93sSN6NM2pKPy+bVOoacR5RC2+c="
  [mod."github.com/xeipuuv/gojsonpointer"]
    version = "v0.0.0-20190905194746-02993c407bfb"
    hash = "sha256-/u+qznDY8cnECZYIgSMRpKVWs04yAkW6EoGhqt+t73g="
  [mod."github.com/zclconf/go-cty"]
    version = "v1.13.0"
    hash = "sha256-2hMDPoptLAB5o2bAyee1jPenOAXnVNGE+dStn0dgQzI="
  [mod."go.opencensus.io"]
    version = "v0.24.0"
    hash = "sha256-4H+mGZgG2c9I1y0m8avF4qmt8LUKxxVsTqR8mKgP4yo="
  [mod."golang.org/x/crypto"]
    version = "v0.24.0"
    hash = "sha256-wpxJApwSmmn9meVdpFdOU0gzeJbIXcKuFfYUUVogSss="
  [mod."golang.org/x/mod"]
    version = "v0.17.0"
    hash = "sha256-CLaPeF6uTFuRDv4oHwOQE6MCMvrzkUjWN3NuyywZjKU="
  [mod."golang.org/x/net"]
    version = "v0.26.0"
    hash = "sha256-WfY33QERNbcIiDkH3+p2XGrAVqvWBQfc8neUt6TH6dQ="
  [mod."golang.org/x/oauth2"]
    version = "v0.21.0"
    hash = "sha256-0xgi5k7fxMScMH+rDwXhDqe8raTFHh5ih727jGVS918="
  [mod."golang.org/x/sync"]
    version = "v0.7.0"
    hash = "sha256-2ETllEu2GDWoOd/yMkOkLC2hWBpKzbVZ8LhjLu0d2A8="
  [mod."golang.org/x/sys"]
    version = "v0.21.0"
    hash = "sha256-gapzPWuEqY36V6W2YhIDYR49sEvjJRd7bSuf9K1f4JY="
  [mod."golang.org/x/term"]
    version = "v0.21.0"
    hash = "sha256-zRm7uPBM1+TJkODYHkk/BtN3la5QAaSgslE2hSTm27Y="
  [mod."golang.org/x/text"]
    version = "v0.16.0"
    hash = "sha256-hMTO45upjEuA4sJzGplJT+La2n3oAfHccfYWZuHcH+8="
  [mod."golang.org/x/tools"]
    version = "v0.21.1-0.20240508182429-e35e4ccd0d2d"
    hash = "sha256-KfnS+3fREPAWQUBoUedPupQp9yLrugxMmmEoHvyzKNE="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20240610135401-a8a62080eff3"
    hash = "sha256-ALD1F7/zrM7QUQH+4jXUTOkGkQ6jEflQgPyVOIqSDLw="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20240617180043-68d350f18fd4"
    hash = "sha256-ass/74EkCljwk7DaASDtK2zipn2cZv6tCLKvwONUWgY="
  [mod."google.golang.org/grpc"]
    version = "v1.64.1"
    hash = "sha256-A1+kiePmeqRIdigryUGNJWZiILLacDPtMTEyO6CqDpY="
  [mod."google.golang.org/protobuf"]
    version = "v1.34.2"
    hash = "sha256-nMTlrDEE2dbpWz50eQMPBQXCyQh4IdjrTIccaU0F3m0="
  [mod."gopkg.in/warnings.v0"]
    version = "v0.1.2"
    hash = "sha256-ATVL9yEmgYbkJ1DkltDGRn/auGAjqGOfjQyBYyUo8s8="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."lukechampine.com/blake3"]
    version = "v1.1.6"
    hash = "sha256-pKVTpuCcqGSn8s11Jq33yrXewQLvycuAoxKJEdbZ7rA="
  [mod."oras.land/oras-go/v2"]
    version = "v2.5.0"
    hash = "sha256-hSZIOvcxxSkyHQpNdslPFP5jflkHjddoF5AK7VF7OOA="
  [mod."sigs.k8s.io/release-utils"]
    version = "v0.7.7"
    hash = "sha256-bI/uQ0zlBbM/ZYX/dCCxmToaP7xFmzzjjRe8RRj6Bf8="
  [mod."zombiezen.com/go/nix"]
    version = "v0.0.0-20240320004700-0734e137f7fe"
    hash = "sha256-Xl2TJCZUoWK3FZZbS2FnfuUr2v9JACsTj7NhQ4v5sS8="
